# Generated by Django 6.0.6 on 2026-06-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gift',
            name='recipient_type',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
